doctrine:
    dbal:
      connections:
        default:
          # configure these for your database server
          url: '%env(DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                #type: annotation
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
          string_functions:
            LPAD: DoctrineExtensions\Query\Mysql\Lpad
          numeric_functions:
            ROUND: DoctrineExtensions\Query\Mysql\Round
          datetime_functions:
            #WEEK: DoctrineExtensions\Query\Mysql\Week
            YEARWEEK: DoctrineExtensions\Query\Mysql\YearWeek
            #WEEKOFYEAR: App\DoctrineExtensions\Query\Mysql\WeekOfYear
            YEAR: DoctrineExtensions\Query\Mysql\Year
            MONTH: DoctrineExtensions\Query\Mysql\Month
            HOUR: DoctrineExtensions\Query\Mysql\Hour
            DAY: DoctrineExtensions\Query\Mysql\Day
            RAND: DoctrineExtensions\Query\Mysql\Rand
            JSON_CONTAINS: DoctrineExtensions\Query\Mysql\JsonContains
