# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    serializer: true #dėl error "Neither a service called "jms_serializer.serializer" nor "serializer" is available and no serializer is explicitly configured. You must either enable"

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        #storage_factory_id: session.storage.factory.native// Available options are "cookie_domain", "cookie_httponly", "cookie_lifetime", "cookie_path", "cookie_samesite", "cookie_secure", "enabled", "gc_divisor", "gc_maxlifetime", "gc_probability", "handler_id", "metadata_update_threshold", "name", "save_path", "sid_bits_per_character", "sid_length", "storage_id", "use_cookies".

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        #engines: twig #Available options are "annotations", "assets", "cache", "csrf_protection", "default_locale", "disallow_search_engine_index", "error_controller", "esi", "form", "fragments", "http_client", "http_method_override", "ide", "lock", "mailer", "messenger", "php_errors", "profiler", "property_access", "property_info", "request", "router", "secret", "secrets", "serializer", "session", "ssi", "templating", "test", "translator", "trusted_hosts", "validation", "web_link", "workflows".

#when@test:
#    framework:
#        test: true
#        session:
#            storage_factory_id: session.storage.factory.mock_file
