monolog:
    handlers:
        syslog_handler:
            type: rotating_file
            path: "%kernel.logs_dir%/syslog/%kernel.environment%.log"
            level: error
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: php://stderr
            level: warning
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            level: debug
            channels: ["!event", "!doctrine"]
